### ISSUE TITLE
Add service item: Link verification

### ISSUE THREAD

**Issue by RajeshVimal** [ashishamnet/quotecreationtool#1]
Please add the service items that are highlighted in yellow in the attached excel.
[Service descriptions_Alt text & Multimedia_Jan '23.xlsx](https://github.com/ashishamnet/quotecreationtool/files/10350641/Service.descriptions_Alt.text.Multimedia_Jan.23.xlsx)

**Comment by RajeshVimal** [comment]
Please use the attached excel. I have added few more service items.
[Service descriptions_Alt text & Multimedia_Jan '23.xlsx](https://github.com/ashishamnet/quotecreationtool/files/10351240/Service.descriptions_Alt.text.Multimedia_Jan.23.xlsx)

**Comment by Srikanth-Amnet** [comment]
Requested details added with default selection

**Comment by RajeshVimal** [comment]
Hi Srikanth,

 

I haven’t seen the newly added processes on the platform. Please advise.

 

Best,

Rajesh Kumar

**Comment by Srikanth-Amnet** [comment]
'**Add on: link verification**' already added in service process items. Pls. check and confirm
