### ISSUE TITLE
Bug: Fields become empty

### ISSUE THREAD

**Issue by RajeshVimal** [ashishamnet/quotecreationtool#10]
Hi,

I tried to edit the below quote, when I change the third line item, the first row values become empty. Please investigate.

https://digita11y.amnet.com/project-quote/edit-quote/91

![image](https://user-images.githubusercontent.com/9881234/217254900-37307b2a-8bd8-48b5-9a66-694767f32801.png)

**Comment by Srikanth-Amnet** [comment]
Hi Rajesh, 

Good Morning.

The above mentioned issue has been fixed and moved staging environment. Can you Pls. check and share your inputs.

Thanks & Regards,
Srikanth M

**Comment by RajeshVimal** [comment]
Thanks, Srikanth.

 

This is fixed and closed the issue in GitHub.

 

Best,

Rajesh Kumar
