### ISSUE TITLE
Weekly and Monthly report - Auto email

### ISSUE THREAD

**Issue by RajeshVimal** [ashishamnet/quotecreationtool#11]
Please send me the weekly update email to the below group?

'CoreAccessibilityTeam' <coreaccessibilityteam@amnet-systems.com>

Time period (Weekly): From Monday to Sunday
On every Monday before 10 AM, the email should have been sent to the group.

Time period (Monthly): From 28th to 27th
On every 28th before 10 AM, the email should have been sent to the group.

Template is attached here.

[Weekly report template.xlsx](https://github.com/ashishamnet/quotecreationtool/files/10733134/Weekly.report.template.xlsx)

**Comment by ashishamnet** [comment]
Make this email address configurable from .env so that if we have to change we should be able to change it from .env and at one place

these days should also be configured in array, down the line we will create a configuration page

**Comment by Srikanth-Amnet** [comment]
Hi Rajesh,

This to inform you that, weekly and monthly report notification has been enabled for project quote. can you pls. check and confirm the same.

**Note:** For testing purpose your and my email address only added. Access this URL for https://accessibilityproductdemo.amnet-systems.com/project-quote/report-notification trigger the email

Thank you!

**Comment by RajeshVimal** [comment]
Hi Srikanth,

 

This is verified. Please move it to the live server. It will help me to verify the data with current value.

 

Best,

Rajesh Kumar

**Comment by Srikanth-Amnet** [comment]
Hi Rajesh,

As per your request we have moved the changes to prod. can you pls check and confirm. then I will configure to send notifications automatically.

For now you can use this URL for trigger the notification manually - https://digita11y.amnet.com/project-quote/report-notification

**Comment by RajeshVimal** [comment]
Thanks, Srikanth. This is confirmed.

 

Best,

Rajesh Kumar

**Comment by RajeshVimal** [comment]
Hi Srikanth,

per our discussion, please include an additional column for Working in progress and put all the values irrespective of date selection. Work In Progress (Till date)

**Comment by Srikanth-Amnet** [comment]
Hi Rajesh,

I have added the Over all WIP status values in weekly and monthly report email notification.

Pls. check and confirm

Thanks & Regards, 
Srikanth M

**Comment by RajeshVimal** [comment]
This is verified, Srikanth.

 

Please proceed.

 

Best,

Rajesh Kumar

**Comment by Srikanth-Amnet** [comment]
Hi Rajesh,

Weekly and monthly reports notifications has been deployed at prod environment. 

Every Monday at 9AM, you will receive the weekly report.
Every month on the 28th at 9AM, you will receive the monthly report.

The notification email has changed to 'CoreAccessibilityTeam'

Thanks & Regards,
Srikanth M

**Comment by RajeshVimal** [comment]
Thanks, Srikanth.

 

Best,

Rajesh Kumar
