### ISSUE TITLE
Add user

### ISSUE THREAD

**Issue by RajeshVimal** [ashishamnet/quotecreationtool#12]
Could you please provide access to the below email ID? He is one of the team leaders who work on the higher education service.

'Hariprasad Narayanan' [hariprasad.narayanan@amnet-systems.com]

**Comment by Srikanth-Amnet** [comment]
Access Provided.

Login password: Amnet@123456

You can reset the password

**Comment by RajeshVimal** [comment]
Thanks, Srikanth.

 

Best,

Rajesh Kumar

**Comment by ashishamnet** [comment]
@RajeshVimal can we close this
