### ISSUE TITLE
Remove delivery date for rejected status

### ISSUE THREAD

**Issue by RajeshVimal** [ashishamnet/quotecreationtool#14]
Please remove the delivery date if the status is other than approved/delivered. Also, include a status called "on Hold" in the Quote status option

![image](https://user-images.githubusercontent.com/9881234/230575459-4c45f859-327f-4f68-a3c4-a23476e07068.png)

**Comment by Srikanth-Amnet** [comment]
Hi Rajesh,

Pls. close this ticket. it's already fixed and deployed

Thanks & Regards,
Srikanth M

**Comment by RajeshVimal** [comment]
Verified

**Comment by RajeshVimal** [comment]
Thanks, Srikanth. I have closed all the tickets.

 

Best,

Rajesh Kumar
