### ISSUE TITLE
Dashboard - shifting order of Wip and Approval

### ISSUE THREAD

**Issue by RajeshVimal** [ashishamnet/quotecreationtool#15]
Hi team,

Please shift the order of Wip and Approval in the reports tab. The approval should come first and then WIP.

![image](https://user-images.githubusercontent.com/9881234/234183942-600653c5-1e68-47b3-9398-e75436346375.png)

**Comment by Srikanth-Amnet** [comment]
Hi Rajesh,

Good Morning!

Column shifting modifications are implemented at staging. Please take a look and share your inputs

https://accessibilityproductdemo.amnet-systems.com/project-quote/dashboard

**Comment by RajeshVimal** [comment]
This is verified, Srikanth. Please move it to live.

 

Best,

Rajesh Kumar

**Comment by Srikanth-Amnet** [comment]
Hi Rajesh,

Changes has deployed at prod

https://digita11y.amnet.com/project-quote/dashboard

Thanks & Regards,
Srikanth M
