### ISSUE TITLE
Adding Complexity

### ISSUE THREAD

**Issue by RajeshVimal** [ashishamnet/quotecreationtool#16]
Hi,

Please add the complexity called "Flat". If possible, please provide a provision to add it on our own.

**Comment by Srikanth-Amnet** [comment]
Hi Rajesh,

The complexity add option has been enabled and deployed at prod

the option available under utility menu

https://digita11y.amnet.com/project-quote/dashboard

Thanks & Regards,
Srikanth M

**Comment by RajeshVimal** [comment]
Verified
