### ISSUE TITLE
Week-wise details - Dashboard (High Priority)

### ISSUE THREAD

**Issue by RajeshVimal** [ashishamnet/quotecreationtool#17]
Hi,

Similar to Monthly quote dashboard, we want to see the following data for weekly analysis. Week-wise data should match the Monthly data. Weeks starts from Monday to Sunday.

1. Approved.
2. Working in progress
3. Delivered

![image](https://github.com/ashishamnet/quotecreationtool/assets/9881234/759300cd-48c8-41bf-850c-e2a241459011)

**Comment by Srikanth-Amnet** [comment]
Hi Rajesh,

Changes has been deployed at staging server. pls share your inputs

**Comment by ashishamnet** [comment]
@RajeshVimal  any update on this?

**Comment by AM10715** [comment]
@all issue is tested and they are fixed.

Thanks and Regards,
Adavan T

**Comment by RajeshVimal** [comment]
The pages are empty. please check.
![image](https://github.com/ashishamnet/quotecreationtool/assets/9881234/fbaed873-364f-4d5b-854b-e298403881bc)

There was no job in working in progress but weekly dashboard is showing some values.
![image](https://github.com/ashishamnet/quotecreationtool/assets/9881234/36602c2a-e21b-4f19-bd84-15790ac822c2)

Can you revisit the weekly dashboard and make the necessary changes?

**Comment by Srikanth-Amnet** [comment]
Hi @RajeshVimal,

In our earlier conversation we are finalized when unit name is **page** then only we are calculating **page count**. if not satisfied the condition its show **'-'**

![image](https://github.com/ashishamnet/quotecreationtool/assets/122095781/0877d0da-25aa-48c9-ba9a-85774926029b)

weekly dashboard shown details are correct. there is some quotes are found in the particular date range

![image](https://github.com/ashishamnet/quotecreationtool/assets/122095781/990416e3-2b23-40cb-8ba4-00e196c7a90e)


Correct me if anything wrong

**Comment by RajeshVimal** [comment]
Inprogress should not be considered as working in progress. Working in progress something we call if the job is approved, and we started working on it.

**Comment by Srikanth-Amnet** [comment]
@RajeshVimal Changes are deployed at staging. pls. take a look and share your inputs

**Comment by RajeshVimal** [comment]
1. Please include the current weekly status in the dashboard. (10th July - 16 July)
![image](https://github.com/ashishamnet/quotecreationtool/assets/9881234/e2b459b2-45b9-46b1-913e-84e7b9fc0d98)

2. The working in progress value should be filled in based on the respective weeks. Currently, the working in progress are empty. I assume, it is getting updated.

**Comment by Srikanth-Amnet** [comment]
@RajeshVimal 
Changes are done and deployed at staging. Can you pls. take a look and share your feedback accordingly

**Comment by RajeshVimal** [comment]
Both are verified at staging. Please move it to the live server. Then only, I can verify them with the help of current data.

**Comment by AM10715** [comment]
The current weekly is updated 
Work in progress value is in respective weeks
In progress is not considered as work in progress. Only approved quotes are considered as work in progress
pages are showing in the weekly and monthly quote analysis
above mentioned areas are tested and it is working fine in staging.

**Comment by RajeshVimal** [comment]
Weekly report dashboard value is not matching with the data exported from title-wise tracker.

**Comment by RajeshVimal** [comment]
The current week data should show the entire working in progress irrespective of date filters. This will help us to see the outstanding value.

**Comment by Srikanth-Amnet** [comment]
@RajeshVimal Changes are deployed at prod. pls. check and confirm

**Comment by ashishamnet** [comment]
> @RajeshVimal Changes are deployed at prod. pls. check and confirm

Any update @RajeshVimal ?

**Comment by RajeshVimal** [comment]
@ashishamnet  - I am seeing huge variation is in work in progress value. The old quotes are being moved to the title-wise tracker, therefore the value becomes huge.


![image](https://github.com/ashishamnet/quotecreationtool/assets/9881234/317ce883-cc14-4611-99f8-816f4d519022)

![image](https://github.com/ashishamnet/quotecreationtool/assets/9881234/ac785c06-19f6-4f32-9684-f1cb06473193)

**Comment by Srikanth-Amnet** [comment]
@RajeshVimal 

We have updated the quote service process status based on the quote status. 
Note: **Applicable only for delivered quotes with WIP service process**

Pls. share your inputs

**Comment by RajeshVimal** [comment]
Please update the weekly dashboard value as discussed.

Approved value - from approved date and to approved date.
Working in progress - the titles which are approved but not yet delivered.

**Comment by RajeshVimal** [comment]
It's verified.
