### ISSUE TITLE
Title-wise - tracker (High Priority)

### ISSUE THREAD

**Issue by RajeshVimal** [ashishamnet/quotecreationtool#18]
Hi,

Once the quote is approved, the title-wise details should be shown in the title-wise tracker. We will update the delivery status there as well. template is attached.

[Title-wise tracker.xlsx](https://github.com/ashishamnet/quotecreationtool/files/11484901/Title-wise.tracker.xlsx)

**Comment by Srikanth-Amnet** [comment]
Hi Rajesh,

Changes has been deployed at staging server. pls share your inputs

**Comment by RajeshVimal** [comment]
Hi Srikanth,

Please see my observations below.

1. Each entry should be shown for each title, irrespective of subitems within the service. The total value should be sum of all the sub items.
![image](https://github.com/ashishamnet/quotecreationtool/assets/9881234/872a88bd-f426-4d2f-9008-6c22dbce8c1c)

2. Once all the titles under the order no. is marked as delivered in the title-wise tracker, the respective order should be marked as delivered automatically.
![image](https://github.com/ashishamnet/quotecreationtool/assets/9881234/8bdfbb2b-779b-4e8c-b4b4-a2d5f4a0b54c)

![image](https://github.com/ashishamnet/quotecreationtool/assets/9881234/85791af5-d670-427c-ad70-57be00da1870)

3. There should not be any status like Waiting for approval. The system should push the title to the title-wise tracker once the status is marked as approved. please correct it.
![image](https://github.com/ashishamnet/quotecreationtool/assets/9881234/c99afa21-c3b1-4135-a6af-26c05dc80d79)

4. Please remove the status like approved, in progress and waiting for approval from the title-wise tracker.

5. Please include download option to export the data as dashboard.

6. Please include the time period along with the week numbers.
![image](https://github.com/ashishamnet/quotecreationtool/assets/9881234/1166343d-a21c-4da8-b956-bfbd0e9ea2ff)

7. I can confirm the weekly report data after implementing the download options.

**Comment by RajeshVimal** [comment]
Can you provide an update on the expected completion date?

**Comment by ashishamnet** [comment]
> Can you provide an update on the expected completion date?

@RajeshVimal build deployed to dev please take a look when you get chance

**Comment by RajeshVimal** [comment]
1. Actual schedule date for ZZ002 is June 23. Out of three job, I have selected June 30 as delivered, but system accepts the date. It should not accept the data exceed the actual schedule date for order number.

![image](https://github.com/ashishamnet/quotecreationtool/assets/9881234/d47e0021-5822-4399-bc5d-748134a75d62)

![image](https://github.com/ashishamnet/quotecreationtool/assets/9881234/f7b0d966-2877-4122-82c4-f06a3c948786)

2. After marked as delivered for three jobs under ZZ002, the titles are gone. They're missing in the title-wise tracker.

![image](https://github.com/ashishamnet/quotecreationtool/assets/9881234/e7386214-4aa3-493b-bfce-4a5b0d0afe3f)

3. Title-wise tracker - The downloaded report has the actual value . Could you please insert one more column and convert them into USD as you did in the dashboard report.

**Comment by Srikanth-Amnet** [comment]
Hi Rajesh,

The recent changes are deployed at staging. Pls check and share your inputs.

Thanks & Regards,
Srikanth M

**Comment by AM10715** [comment]
@all above Issues are tested and they are fixed.

Thanks and Regards,
Adavan T

**Comment by RajeshVimal** [comment]
The status should be working in progress.
![image](https://github.com/ashishamnet/quotecreationtool/assets/9881234/54da2bdf-d0a5-4a2c-b3cd-5135d07f86ac)

The delivered date should be the date of the end title's date.
![image](https://github.com/ashishamnet/quotecreationtool/assets/9881234/c728a75f-8372-4020-98c7-288cc33356ae)

**Comment by Srikanth-Amnet** [comment]
@RajeshVimal the changes are done and deployed at staging. pls share your inputs accordingly
