### ISSUE TITLE
Test environment (email deactivation)

### ISSUE THREAD

**Issue by RajeshVimal** [ashishamnet/quotecreationtool#19]
Hi,

Please send email to me alone from the testing environment.

Team is getting confused when they receive the overdue emails from the digitally (testing env).

![image](https://github.com/ashishamnet/quotecreationtool/assets/9881234/8a65fca5-21f0-4aac-b2ee-d09afc621e5c)

**Comment by Srikanth-Amnet** [comment]
Hi Rajesh, Service group emails are replaced with your official email at staging server.

**Comment by ashishamnet** [comment]
@RajeshVimal check and confirm if we can close this

**Comment by RajeshVimal13** [comment]
verified
