### ISSUE TITLE
Request to show delivery date in the dashboard

### ISSUE THREAD

**Issue by RajeshVimal** [ashishamnet/quotecreationtool#2]
1. Delivery date should be visible in he dashboard. Even it is delivered, it should show the date of delivered.
![image](https://user-images.githubusercontent.com/9881234/210738083-5c300922-0290-4bf2-8206-425471836336.png)

2. The report should filter and show the values according to the status. If we select the delivery, it should show only the value that delivered under the selected dates.
![image](https://user-images.githubusercontent.com/9881234/210738150-33cec017-488c-4ed6-8874-f1590d9f2314.png)

**Comment by Srikanth-Amnet** [comment]
1. Delivery date has been displayed when the date is exist
2. Report filters added. if you selected have any status then relevant details only display
3. Same filter changes are applied for download report

**Comment by RajeshVimal** [comment]
Verified, all the changes are fixed as requested.

**Comment by RajeshVimal** [comment]
This is closed, Srikanth.

 

Best,

Rajesh Kumar
