### ISSUE TITLE
Dashboard - Monthly report (Consider pages only)

### ISSUE THREAD

**Issue by RajeshVimal** [ashishamnet/quotecreationtool#20]
In the Monthly quote analysis, please account only the pages. I have noticed that words are taken into an account. Generally, the words count would be higher in number like 14k words, so on.

![image](https://github.com/ashishamnet/quotecreationtool/assets/9881234/cc356b88-2d2c-4682-bd10-c6a416799a01)

**Comment by Srikanth-Amnet** [comment]
Hi

We need more clarification about this.

Thanks & Regards
Srikanth M

**Comment by Srikanth-Amnet** [comment]
@RajeshVimal We are not calculating the word count at any where in the tool. we calculating the units counts and showing as pages

**Comment by RajeshVimal** [comment]
In May, we quoted for translation service, the unit is words. Therefore, in the dashboard, word counts were accounted and showing huge number as pages.
![image](https://github.com/ashishamnet/quotecreationtool/assets/9881234/4306dce3-1418-43c6-93cb-12027bffd6db)


![image](https://github.com/ashishamnet/quotecreationtool/assets/9881234/a094a991-32ce-4dac-9bbf-7131c984af04)

**Comment by Srikanth-Amnet** [comment]
@RajeshVimal the entered units values **194988**. I think this is typo error. As of now we are considering **Units** as **pages**. Units not accept strings like alphabets and we are not automated the document page counts. 

Pls. share your inputs

**Comment by Srikanth-Amnet** [comment]
@RajeshVimal the changes are done and deployed at staging. pls share your inputs accordingly
