### ISSUE TITLE
Weekly Dashboard - Interactive month selector

### ISSUE THREAD

**Issue by RajeshVimal** [ashishamnet/quotecreationtool#22]
Currently, it is getting updated dynamically by adding the weeks. So, we were unable to see the progress of the respective month's volume. Please show the current month's week data in the weekly dashboard.  And provide provision to see the previous month's weekly data.

**Comment by Srikanth-Amnet** [comment]
Hi @RajeshVimal 

Changes are deployed at our staging. Pls. check and share your inputs

**Comment by RajeshVimal** [comment]
Please don't apply the billing cycle here. Week 1 should be considered if the presence of respective month's date more than three days. For example: 28th Aug (Mon) to 3rd September (Sun) - this should be considered as last week of the previous month which is August. Week 1 of September should be 4th Sep to 10th Sep

**Comment by AM10715** [comment]
@RajeshVimal changes are deployed and tested in staging. Please check and confirm.

**Comment by RajeshVimal** [comment]
This is verified.
