### ISSUE TITLE
Quote Dashboard - Hold Option

### ISSUE THREAD

**Issue by RajeshVimal** [ashishamnet/quotecreationtool#23]
Please include the option named as "Hold". If we mark the quote as Hold, it should be added for the overall quote value and should be excluded for Waiting for approval value. This option will be helpful to mark the quote which we pending more than a month.

**Comment by Srikanth-Amnet** [comment]
Hi @RajeshVimal 

Changes are deployed at our staging. Pls. check and share your inputs

**Comment by RajeshVimal** [comment]
Hi Srikanth,

Quotes:
The option "Hold" should be enabled only if the quote is in "Waiting for approval". If the quote status is "Hold", the user should modify it to either approved or rejected.

Title-wise tracker:
Please add option "Hold" in the title-wise tracker. Sometimes, a few titles under the quote might be put on hold due to some queries.

**Comment by AM10715** [comment]
@RajeshVimal changes are deployed and tested. Please check and confirm.

**Comment by RajeshVimal** [comment]
This is verified.
