### ISSUE TITLE
Dashboard - Include WIP and other minor changes

### ISSUE THREAD

**Issue by RajeshVimal** [ashishamnet/quotecreationtool#5]
1. Remove the primary service column from Reports tab.
![image](https://user-images.githubusercontent.com/9881234/213389549-5babd6e9-786e-4f0a-9388-ef80a6d30c34.png)

2. Change the table header as below:
    a. In Progress - QIP
    b. Waiting for Approval = WFA

3. Include the WIP details = Approved value - delivered value

**Comment by ashishamnet** [comment]
@RajeshVimal if we remove service column then how you will come to know about service if "ALL" is selected?

**Comment by RajeshVimal** [comment]
Hi Ashish,

 

We will see the service-wise details in the Quote tab if needed. Here (Reports), we are including an additional column, removing this column will give some space to accommodate the new column. Senthil wants to see the customer-wise value in the report. Also, we can download the report to see the service-wise details. 

 

Our request is to hide the information from the table.

 

Let me know your thoughts.

 

Best,

Rajesh Kumar
