### ISSUE TITLE
Dashboard - Monthly data chart

### ISSUE THREAD

**Issue by RajeshVimal** [ashishamnet/quotecreationtool#6]
Please remove both bar chart and Pie chart. Show the following grid in a table format (attached).

[Month data format.xlsx](https://github.com/ashishamnet/quotecreationtool/files/10454868/Month.data.format.xlsx)

All the values should be in USD. Conversion rate is below for computation.

Euro = Euro * 1.12 = USD
CAD = CAD * 0.77 = USD
GBP = GBP * 1.31 = USD

**Comment by Srikanth-Amnet** [comment]
Hi Rajesh,

Can you Pls. share all the currency conversion rate.

And I think Euro to USD conversion should be division like USD=Euro / 1.2. can you pls confirm the formula.

Thank you!

**Comment by RajeshVimal** [comment]
Hi Srikanth,

 

Here are the details.

 


$     = $*1* INR 70


£     = £ *1.31* INR 70


€     = € *1.12* INR 70


AUD = AUD*0.70* INR 70


CAD = CAD*0.77* INR 70


ZAR = CAD*0.079* INR 70


SGD = CAD*0.75* INR 70

 

 

Best,

Rajesh Kumar
